name: Build and Publish

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (v0.2.1, etc.)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Debug directory structure
      run: |
        pwd
        ls -la
        # Check if pyproject.toml exists
        if [ -f "pyproject.toml" ]; then
          echo "pyproject.toml found"
        else
          echo "pyproject.toml NOT found"
          find . -name "pyproject.toml"
        fi
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        # Install dependencies like in docs.yml to ensure consistency
        pip install statsmodels scikit-learn cartopy matplotlib xarray pandas numpy
        # Install the package in development mode first, just like in docs.yml
        pip install -e .
    
    - name: Build package
      run: |
        # Build the package
        python -m build
    
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*